Repository waku-org/go-waku, pull requests merged in 2023-09, with the labels that each got.

#699 fix: allow mixing named and static shards
  waku/v2/discv5/discover.go
  waku/v2/node/localnode.go
  waku/v2/protocol/shard.go
Labels: E:2023-qa

#701 fix(rln-relay): sync from deployed block number
  waku/v2/protocol/rln/group_manager/dynamic/web3.go
  waku/v2/protocol/rln/web3/web3.go
Labels: E:2023-rln

#702 feat: store and retrieve valid merkle roots in RLN db
  waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
  waku/v2/protocol/rln/group_manager/dynamic/metadata.go
  waku/v2/protocol/rln/group_manager/dynamic/metadata_test.go
  waku/v2/protocol/rln/group_manager/dynamic/web3.go
  waku/v2/protocol/rln/group_manager/root_tracker.go
  waku/v2/protocol/rln/web3/web3.go
Labels: E:2023-rln

#708 chore(rln-relay): use the only key from keystore if only 1 exists
  .codeclimate.yml
  cmd/waku/flags_rln.go
  cmd/waku/node_rln.go
  cmd/waku/options.go
  examples/chat2/exec.go
  examples/chat2/flags.go
  examples/chat2/options.go
  waku/cliutils/cli.go
  waku/v2/node/wakunode2_rln.go
  waku/v2/node/wakuoptions.go
  waku/v2/node/wakuoptions_rln.go
  waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
  waku/v2/protocol/rln/keystore/keystore.go
  waku/v2/protocol/rln/onchain_test.go
Labels: E:2023-rln

#712 chore: add tls/ws to address factory
  waku/v2/node/wakuoptions.go
Labels: E:2023-qa

#704 fix: loop counter for writing multiaddresses in enr
  waku/v2/protocol/enr/localnode.go
Labels: E:2023-qa

#715 chore(rln-relay): clean up nullifier table every MaxEpochGap
  waku/v2/protocol/rln/nullifier_log.go
  waku/v2/protocol/rln/onchain_test.go
  waku/v2/protocol/rln/rln_relay_test.go
  waku/v2/protocol/rln/waku_rln_relay.go
Labels: E:2023-rln

#718 feat: append RLN proofs when posting messages in REST/RPC
  cmd/waku/node.go
  cmd/waku/server/no_rln.go
  cmd/waku/server/rest/debug.go
  cmd/waku/server/rest/debug_api.yaml
  cmd/waku/server/rest/debug_test.go
  cmd/waku/server/rest/relay.go
  cmd/waku/server/rest/relay_api.yaml
  cmd/waku/server/rest/relay_test.go
  cmd/waku/server/rest/runner.go
  cmd/waku/server/rest/store.go
  cmd/waku/server/rest/store_api.yaml
  cmd/waku/server/rest/store_test.go
  cmd/waku/server/rest/utils.go
  cmd/waku/server/rest/utils_test.go
  cmd/waku/server/rest/waku_rest.go
  cmd/waku/server/rest/waku_rest_test.go
  cmd/waku/server/rln.go
  cmd/waku/server/rpc/admin.go
  cmd/waku/server/rpc/admin_test.go
  cmd/waku/server/rpc/codec.go
  cmd/waku/server/rpc/coded_test.go
  cmd/waku/server/rpc/debug.go
  cmd/waku/server/rpc/debug_test.go
  cmd/waku/server/rpc/filter.go
  cmd/waku/server/rpc/filter_test.go
  cmd/waku/server/rpc/relay.go
  cmd/waku/server/rpc/relay_test.go
  cmd/waku/server/rpc/rpc_type.go
  cmd/waku/server/rpc/runner.go
  cmd/waku/server/rpc/store.go
  cmd/waku/server/rpc/store_test.go
  cmd/waku/server/rpc/util_test.go
  cmd/waku/server/rpc/utils.go
  cmd/waku/server/rpc/waku_rpc.go
  cmd/waku/server/rpc/waku_rpc_test.go
  waku/v2/node/wakunode2_no_rln.go
Labels: E:2023-rln

#722 Fix/filterv2
  waku/v2/protocol/filter/client.go
  waku/v2/protocol/filter/filter_test.go
  waku/v2/protocol/filter/pb/waku_filter_v2.pb.go
  waku/v2/protocol/filter/pb/waku_filter_v2.proto
  waku/v2/protocol/filter/server.go
  waku/v2/protocol/filter/subscriptions_map.go
Labels: bug

#719 feat(rln-relay): ensure execution order for pubsub validators
  examples/chat2/exec.go
  waku/v2/node/wakunode2.go
  waku/v2/node/wakunode2_rln.go
  waku/v2/node/wakuoptions.go
  waku/v2/protocol/envelope.go
  waku/v2/protocol/relay/validators.go
  waku/v2/protocol/relay/validators_test.go
  waku/v2/protocol/relay/waku_relay.go
  waku/v2/protocol/relay/waku_relay_test.go
  waku/v2/protocol/rln/common.go
  waku/v2/protocol/rln/waku_rln_relay.go
Labels: E:3.2: Basic DoS protection in production

#743 feat(rln-relay): use zerokit 0.3.4 to obtain number of leaves set in merkle tree
  examples/basic2/go.mod
  examples/basic2/go.sum
  examples/chat2/go.mod
  examples/chat2/go.sum
  examples/filter2/go.mod
  examples/filter2/go.sum
  examples/rln/go.mod
  examples/rln/go.sum
  flake.nix
  go.mod
  go.sum
  waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
Labels: E:3.2: Basic DoS protection in production

#742 feat: allow running rln with no credentials
  cmd/waku/flags_rln.go
  cmd/waku/rlngenerate/flags.go
  waku/v2/node/wakunode2.go
  waku/v2/node/wakunode2_rln.go
  waku/v2/protocol/rln/group_manager/dynamic/dynamic.go
  waku/v2/protocol/rln/keystore/keystore.go
Labels: E:3.2: Basic DoS protection in production

#757 ci: use wakuorg Docker Hub organization
  Makefile
  README.md
  ci/Jenkinsfile.docker
  docs/operators/how-to/run-with-rln.md
  docs/operators/quickstart.md
  scripts/linux/README.md
  scripts/linux/docker-run.sh
Labels: infra

#758 ci: drop pushing commit tags for Docker
  ci/Jenkinsfile.docker
Labels: infra

#767 ci: use latest and stable Docker tags based on job name
  ci/Jenkinsfile.docker
Labels: infra
